# Generated by Django 5.0.6 on 2024-07-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_application', '0002_letterofcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofcredit',
            name='advising_bank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='applicant_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='beneficiary_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='confirming_bank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='issuing_bank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='lc_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='negotiating_bank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
